world:
  is_locked: false
  short_name: takp
  long_name: TAKP2 Test (Xack)
  wan_address: 0.0.0.0
  lan_address: 0.0.0.0
  max_clients: -1
  intranet_ip: 127.0.0.1
  intranet_port: 9001
  telnet_is_enabled: true
  telnet_ip: 127.0.0.1
  telnet_port: 9000
  shared_key: iasodjaoisjdiaosjdsaiojdsa
ucs:
  host: 0.0.0.0
  port: 7778
database:
  db: takp
  host: 127.0.0.1
  port: 3307
  username: takp
  password: takppass
query_serv:
  db: takp
  host: 127.0.0.1
  port: 3307
  username: takp
  password: takppass
zone:
  default_status: 0
  port_min: 7000 # min port zones occupy
  port_max: 7400 # max port zones occupy
  max_zones: 5 # Number of zones to start with manager
login_server:
- port: 5998
  account:
  password:
  host: login.projecteq.net
  type: 0
dir:
  patches: assets/patches/
  opcodes: assets/opcodes/
  shared_memory: shared/
  lua_modules: quests/lua_modules/
  quests: quests/
  plugins: quests/plugins/
  maps: maps/
  logs: logs/
other:
  talkeq: talkeq
  githubeq: githubeq