name: ubuntu-20.04

on:
  push:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write


    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set Version
      run: make set-version

    - name: Get CMake
      uses: lukka/get-cmake@latest

    - name: Install Dependencies
      run: sudo apt install -y --no-install-recommends build-essential libtool cmake curl debconf-utils  git liblua5.1-0  liblua5.1-0-dev libluabind-dev libmysql++-dev  libsodium-dev  libmysqlclient-dev libssl-dev lua5.1  minizip make locales nano open-vm-tools unzip uuid-dev iputils-ping zlibc wget libcurl4-openssl-dev gdb libyaml-cpp-dev libgtest-dev

    - name: Run CMake
      run: mkdir -p build && cd build && cmake -DEQEMU_BUILD_LOGIN=ON -DEQEMU_BUILD_LUA=ON -G 'Unix Makefiles' ..

    - name: Make
      run: cd build && make

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        path: './build/bin/'
        type: 'tar'
        filename: 'linux-${{ env.VERSION }}.${{ github.run_number }}.tar.gz'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.VERSION }}.${{ github.run_number }}"
        prerelease: false
        title: "${{ env.VERSION }}.${{ github.run_number }}"
        files: |
          build/bin/${{ env.VERSION }}.${{ github.run_number }}.tar.gz
